### ISSUE TITLE
Issue with not passing an options object to the constructor

### ISSUE THREAD

**Issue by jspizziri** [jspizziri/sequelize-connect#14]
Ref: https://github.com/jspizziri/sequelize-connect/issues/13

**Comment by pinn3** [comment]
This problem only occurs if we declare a new connection without maintaining the argument order, for example when using a connection string instead of separate arguments.

What are your thoughts on changing the way `Connection` receives its arguments?
I'm thinking that it might be cleaner and more convenient to accept an arguments object instead.

As it is now, In order to pass in the `options`, `discover`, `matcher` and `logger` arguments, you have to specify the other arguments to be null or undefined. This is quite ugly and confusing, especially if you only use a connection string. It would result in something like this:

``` js
const Connection = require('sequelize-connection')

const discover = [__dirname + '/models', ...]

const orm = new Connection(
  'postgres://user:password@localhost:5432/database', // database argument, which in this case is a connection string
  null, // user argument, has to be set to null as we use a connection string but is required to maintain the argument order
  null, // password argument, same thing here
  { dialect: 'postgres' }, // options argument, neccesary at the moment as it defaults to an empty object otherwise, overwriting the dialect and port from the connection string
  discover, // until we get to here, where the discover argument is accepted
  null, // matcher argument, same as before
  true // and then we can specify the logger flag
)
```

What I'm suggesting would be:

``` js
const Connection = require('sequelize-connection')

const orm = new Connection({
  database: 'postgres://user:password@localhost:5432/database',
  discover: [__dirname + '/models', ...]
})
```

I can make the changes and submit a pull request if you're fine with this.

**Comment by jspizziri** [comment]
@pinn3,

I'd be on board with providing all the DB specific info as an object, e.g. `{ database: , username: , password: }` but I'd like to leave discover, and logger as separate options. If you submit a PR I'll merge it (BC would be nice as well if possible).
